### ISSUE TITLE
Uncaught TypeError: Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by itswadesh** [shershen08/vue-masonry-plugin-demo#1]
`import { VueMasonryPlugin } from '../../node_modules/vue-masonry/src/masonry.plugin';` works good.

Where as Browser console says `Uncaught TypeError: Cannot read property 'install' of undefined` while 

`import { VueMasonryPlugin } from 'vue-masonry';`

**Comment by nominalaeon** [comment]
I'm having the same problem, I used `npm install` and have version `0.11.3`

**Comment by shershen08** [comment]
it's because of this - https://github.com/shershen08/vue-masonry/issues/66
please check in a day, I'll have it fixed

**Comment by shershen08** [comment]
closing it here, please follow the main thread - https://github.com/shershen08/vue-masonry/issues/66
